# deploy.yml

service: helloworld
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  app:
    handler: hello.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
